[package]
name = "rustweb"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }
dotenvy = "0.15.7"
sqlx = { version = "0.8.6", features = ["postgres", "chrono", "runtime-tokio"] }
tokio = { version = "1.45.1", features = ["full"] }
